# Assignment-3 (ANN)

Take Multiple-Class Classification Dataset From Kaggle.
1-Data Preprocessing 
2-EDA
3-Train,Test & Split
4-Feature Scaling
5-Model Building
    1-Import Necessary libraries
    2-Add input layer(inputs=no of inputs in dataset=n,weights=random,AF=relu)
    3-Add hidden layer(no of hidden neuron=inputs=2n or n/2,weights=random,AF)
    4-Add output layer(inputs,weights,AF
                      Regression-1,random,relu
                      Binary-1,random,sigmoid
                      Categorical-no of classes,random,softmax)
    5-Configure the learning processs
        (loss function,accuracy,optimizer)
      Regression- (MSE,Gradient/Stochastic/Mini Batch)
      Binary-(binary cross entropy,accuracy,Gradient/Stochastic/Mini Batch)
      Categorical-(categorical cross entropy,accuracy,Gradient/Stochastic/Mini Batch)
    6-Fit the Model(x_train,y_train,batch_size,no of epochs)
6-Test the model

In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv(r'E:\SmartBridge Externship\Assignment-3\Churn_Modelling.csv')

In [3]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
df.shape

(10000, 14)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [6]:
df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [7]:
df.describe()

RowNumber    CustomerId   CreditScore           Age        Tenure  \
count  10000.00000  1.000000e+04  10000.000000  10000.000000  10000.000000   
mean    5000.50000  1.569094e+07    650.528800     38.921800      5.012800   
std     2886.89568  7.193619e+04     96.653299     10.487806      2.892174   
min        1.00000  1.556570e+07    350.000000     18.000000      0.000000   
25%     2500.75000  1.562853e+07    584.000000     32.000000      3.000000   
50%     5000.50000  1.569074e+07    652.000000     37.000000      5.000000   
75%     7500.25000  1.575323e+07    718.000000     44.000000      7.000000   
max    10000.00000  1.581569e+07    850.000000     92.000000     10.000000   

             Balance  NumOfProducts    HasCrCard  IsActiveMember  \
count   10000.000000   10000.000000  10000.00000    10000.000000   
mean    76485.889288       1.530200      0.70550        0.515100   
std     62397.405202       0.581654      0.45584        0.499797   
min         0.000000       1.000000      0.00000        0.000000   
25%         0.000000       1.000000      0.00000        0.000000   
50%     97198.540000       1.000000      1.00000        1.000000   
75%    127644.240000       2.000000      1.00000        1.000000   
max    250898.090000       4.000000      1.00000        1.000000   

       EstimatedSalary        Exited  
count     10000.000000  10000.000000  
mean     100090.239881      0.203700  
std       57510.492818      0.402769  
min          11.580000      0.000000  
25%       51002.110000      0.000000  
50%      100193.915000      0.000000  
75%      149388.247500      0.000000  
max      199992.480000      1.000000

In [8]:
df['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [9]:
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [10]:
df['Geography'].value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [11]:
df['Gender'].value_counts()

Male      5457
Female    4543
Name: Gender, dtype: int64

# Label Encoding

In [12]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Geography']=le.fit_transform(df['Geography'])
df['Gender']=le.fit_transform(df['Gender'])

In [13]:
df['Geography'].value_counts()

0    5014
1    2509
2    2477
Name: Geography, dtype: int64

In [14]:
df['Gender'].value_counts()

1    5457
0    4543
Name: Gender, dtype: int64

In [15]:
df.head()

RowNumber  CustomerId   Surname  CreditScore  Geography  Gender  Age  \
0          1    15634602  Hargrave          619          0       0   42   
1          2    15647311      Hill          608          2       0   41   
2          3    15619304      Onio          502          0       0   42   
3          4    15701354      Boni          699          0       0   39   
4          5    15737888  Mitchell          850          2       0   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

# Independent & Dependent 

In [16]:
df.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [17]:
df.shape

(10000, 14)

In [18]:
x=df.iloc[:,3:13]

In [19]:
x

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619          0       0   42       2       0.00              1   
1             608          2       0   41       1   83807.86              1   
2             502          0       0   42       8  159660.80              3   
3             699          0       0   39       1       0.00              2   
4             850          2       0   43       2  125510.82              1   
...           ...        ...     ...  ...     ...        ...            ...   
9995          771          0       1   39       5       0.00              2   
9996          516          0       1   35      10   57369.61              1   
9997          709          0       0   36       7       0.00              1   
9998          772          1       1   42       3   75075.31              2   
9999          792          0       0   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [20]:
y=df.iloc[:,13:]

In [21]:
y

Exited
0          1
1          0
2          1
3          0
4          0
...      ...
9995       0
9996       0
9997       1
9998       1
9999       0

[10000 rows x 1 columns]

In [22]:
type(x)

pandas.core.frame.DataFrame

In [23]:
type(y)

pandas.core.frame.DataFrame

In [24]:
x=df.iloc[:,3:13].values

In [25]:
x

array([[6.1900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [6.0800000e+02, 2.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [5.0200000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [7.0900000e+02, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [7.7200000e+02, 1.0000000e+00, 1.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [7.9200000e+02, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [26]:
type(x)

numpy.ndarray

In [27]:
x.ndim

2

In [28]:
y=df.iloc[:,13:].values

In [29]:
y

array([[1],
       [0],
       [1],
       ...,
       [1],
       [1],
       [0]], dtype=int64)

# Train,Test & Split

In [30]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [31]:
x.shape

(10000, 10)

In [32]:
y.shape

(10000, 1)

In [33]:
x_train.shape

(8000, 10)

In [34]:
x_test.shape

(2000, 10)

In [35]:
y_train.shape

(8000, 1)

In [36]:
y_test.shape

(2000, 1)

# Feature Scaling

In [37]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
x_train=ss.fit_transform(x_train)
x_test=ss.transform(x_test)

In [38]:
x_train

array([[ 0.16958176,  1.51919821, -1.09168714, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-2.30455945,  0.3131264 ,  0.91601335, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [-1.19119591, -0.89294542, -1.09168714, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.9015152 , -0.89294542,  0.91601335, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-0.62420521,  1.51919821, -1.09168714, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-0.28401079,  0.3131264 , -1.09168714, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [39]:
x_test

array([[-0.55204276,  0.3131264 , -1.09168714, ...,  0.64259497,
         0.9687384 ,  1.61085707],
       [-1.31490297, -0.89294542, -1.09168714, ...,  0.64259497,
        -1.03227043,  0.49587037],
       [ 0.57162971,  1.51919821, -1.09168714, ...,  0.64259497,
         0.9687384 , -0.42478674],
       ...,
       [-0.74791227,  1.51919821,  0.91601335, ...,  0.64259497,
        -1.03227043,  0.71888467],
       [-0.00566991,  0.3131264 ,  0.91601335, ...,  0.64259497,
         0.9687384 , -1.54507805],
       [-0.79945688,  0.3131264 ,  0.91601335, ...,  0.64259497,
        -1.03227043,  1.61255917]])

# Model Building

# Importing Libraries

In [40]:
import tensorflow as tf

In [41]:
tf.__version__

'2.9.1'

In [42]:
import keras as ks

In [43]:
ks.__version__

'2.9.0'

In [44]:
#pip install tensorflow

#pip intsall keras

In [45]:
from keras.models import Sequential
from keras.layers import Dense

In [46]:
model=Sequential()

# Input Layer

In [47]:
model.add(Dense(units=10,kernel_initializer='random_uniform',activation='relu'))

# 1st Hidden Layer

In [48]:
model.add(Dense(units=5,kernel_initializer='random_uniform',activation='relu'))

# 2nd Hidden Layer

In [49]:
model.add(Dense(units=5,kernel_initializer='random_uniform',activation='relu'))

# Output Layer

In [50]:
model.add(Dense(units=1,kernel_initializer='random_uniform',activation='sigmoid'))

# Configure Learning Process

In [51]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

# Fit the Model

In [52]:
model.fit(x_train,y_train,epochs=10,batch_size=32)

Epoch 1/10
250/250 [==============================] - 3s 4ms/step - loss: 0.5568 - accuracy: 0.7959
Epoch 2/10
250/250 [==============================] - 1s 4ms/step - loss: 0.4394 - accuracy: 0.7960
Epoch 3/10
250/250 [==============================] - 1s 3ms/step - loss: 0.4334 - accuracy: 0.7960
Epoch 4/10
250/250 [==============================] - 1s 3ms/step - loss: 0.4292 - accuracy: 0.7960
Epoch 5/10
250/250 [==============================] - 1s 4ms/step - loss: 0.4252 - accuracy: 0.7960
Epoch 6/10
250/250 [==============================] - 1s 3ms/step - loss: 0.4223 - accuracy: 0.8085
Epoch 7/10
250/250 [==============================] - 1s 3ms/step - loss: 0.4206 - accuracy: 0.8214
Epoch 8/10
250/250 [==============================] - 1s 3ms/step - loss: 0.4191 - accuracy: 0.8266
Epoch 9/10
250/250 [==============================] - 1s 3ms/step - loss: 0.4176 - accuracy: 0.8264
Epoch 10/10
250/250 [==============================] - 1s 3ms/step - loss: 0.4164 - accuracy: 0.8290

In [53]:
x_train.shape

(8000, 10)

In [54]:
#8000/32=250

# Test The Model

In [55]:
ypred=model.predict(x_test)

63/63 [==============================] - 0s 2ms/step


In [56]:
ypred

array([[0.22641973],
       [0.344376  ],
       [0.2312764 ],
       ...,
       [0.23097187],
       [0.11108691],
       [0.11400706]], dtype=float32)

In [57]:
y_test

array([[0],
       [1],
       [0],
       ...,
       [0],
       [0],
       [0]], dtype=int64)

In [58]:
#sigmoid 0-1
#threshold value= 0.5 >0.5---->1   /    <0.5---->0
y_pred=ypred>0.5

In [59]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [60]:
x_test[0]

array([-0.55204276,  0.3131264 , -1.09168714, -0.36890377,  1.04473698,
        0.8793029 , -0.92159124,  0.64259497,  0.9687384 ,  1.61085707])

In [61]:
y_test[0]

array([0], dtype=int64)

In [62]:
predict=model.predict([[-0.55204276,  0.3131264 , -1.09168714, -0.36890377,  1.04473698,
        0.8793029 , -0.92159124,  0.64259497,  0.9687384 ,  1.61085707]])

1/1 [==============================] - 0s 65ms/step


In [63]:
predict>0.5

array([[False]])